// react-app/src/App.js
import { Switch, Route, Link, BrowserRouter } from 'react-router-dom';
import Home from './pages/Home.jsx';
import Test from './pages/Test.jsx';

const App = () => {
  return (
    <BrowserRouter>
      <Link to="/">Home</Link>
      <Link to="/test">Test</Link>
      <Switch>
        <Route path="/" exact component={Home} />
        <Route path="/test" component={Test} />
      </Switch>
    </BrowserRouter>
  );
};

export default App;

// svelte-app/src/App.svelte
<script>
  import { Router, Route, Link } from 'svelte-navigator';
  import Home from './routes/Home.svelte';
  import Test from './routes/Test.svelte';
</script>

<Router>
  <Link to="">Home</Link>
  <Link to="test">Test</Link>
  <Route exact path="" component={Home} />
  <Route path="test" component={Test} />
</Router>

<style global lang="postcss">
  @tailwind base;
  @tailwind components;
  @tailwind utilities;
</style>
